providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /conf
    watch: true

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
